# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadratic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\"/\n\x0c\x43oefficients\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"\x1c\n\x08Solution\x12\x10\n\x08solution\x18\x01 \x01(\t2?\n\x0fQuadraticSolver\x12,\n\x0eSolveQuadratic\x12\r.Coefficients\x1a\t.Solution\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COEFFICIENTS']._serialized_start=19
  _globals['_COEFFICIENTS']._serialized_end=66
  _globals['_SOLUTION']._serialized_start=68
  _globals['_SOLUTION']._serialized_end=96
  _globals['_QUADRATICSOLVER']._serialized_start=98
  _globals['_QUADRATICSOLVER']._serialized_end=161
# @@protoc_insertion_point(module_scope)
